version: "3"
services:
  gogs:
    container_name: gogs
    image: gogs/gogs
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - data:/data
      - backup:/backup
    environment:
      - RUN_CROND=true
      - BACKUP_INTERVAL=3d
      - BACKUP_RETENTION=7d

volumes:
  data:
    name: gogs_data
  backup:
    name: gogs_backup
