version: "3"
services:
  gogs:
    container_name: gogs
    image: gogs/gogs
    ports:
      - 3000:3000
    volumes:
      - data:/data
      - backup:/backup
    environment:
      - RUN_CROND=true
      - BACKUP_INTERVAL=3d
      - BACKUP_RETENTION=7d
      - FILE_MAX_SIZE=500
      - MAX_FILES=500

volumes:
  data:
    name: gogs_data
  backup:
    name: gogs_backup

networks:
  default:
    external:
      name: nginx
