---
- name: Basic Setup
  hosts: all
  tasks:
      - name: Update and Upgrade
        ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 3600
            upgrade: dist


      - name: Install Essentials
        ansible.builtin.apt:
            pkg:
                - build-essential
                - git
                - gcc
                - g++
                - make
                - curl
                - wget
                - vim
                - nano
                - apt-transport-https
                - ca-certificates

      - name: Install Python
        ansible.builtin.apt:
            pkg:
                - python3
                - python3-dev
                - python3-pip
                - python3-setuptools
                - python3-virtualenv
                - python-is-python3
