---
- name: Docker Setup
  hosts: all
  tasks:
      - name: Add Docker GPG apt Key
        ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Add Docker Repository
        ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu kinetic stable
            state: present

      - name: Update apt and install docker-ce
        ansible.builtin.apt:
            name: docker-ce
            update_cache: true

      - name: Install Docker Module for Python
        ansible.builtin.pip:
            name: docker

      - name: Add "vineel" user to "docker" group
        ansible.builtin.user:
            name: "vineel"
            groups: "docker"
            append: true
