version: '3'

services:
  db:
    container_name: nextcloud_db
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    command: sh -c 'apt update && apt install cron -y && apache2-foreground'
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - code:/var/www/html
      - config:/var/www/html/config
      - /mnt/nextcloud/data:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.vineelsai.com
      - OVERWRITEPROTOCOL=https
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  code:
    name: nextcloud
  config:
    name: nextcloud-config
  db:
    name: nextcloud-db

networks:
  default:
    external:
      name: nginx

secrets:
  nextcloud_admin_password:
    file: /mnt/nextcloud/secretes/nextcloud_admin_password.txt # put admin password in this file
  nextcloud_admin_user:
    file: /mnt/nextcloud/secretes/nextcloud_admin_user.txt # put admin username in this file
  postgres_db:
    file: /mnt/nextcloud/secretes/postgres_db.txt # put postgresql db name in this file
  postgres_password:
    file: /mnt/nextcloud/secretes/postgres_password.txt # put postgresql password in this file
  postgres_user:
    file: /mnt/nextcloud/secretes/postgres_user.txt # put postgresql username in this file
