version: '3'
services:
  app:
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - nginx_proxy_manager

volumes:
  data:
    name: nginx-proxy-manager-data
  letsencrypt:
    name: nginx-proxy-manager-letsencrypt

networks:
  default:
    external:
      name: nginx
  nginx_proxy_manager:
    name: nginx_proxy_manager
    driver: bridge
