version: '3'
services:
  app:
    container_name: wireguard
    hostname: wireguard
    image: linuxserver/wireguard:latest
    restart: unless-stopped
    ports:
      - '51820:51820/udp'
    volumes:
      - config:/config
      - modules:/lib/modules
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - SERVERURL=144.24.140.207 `#optional`
      - SERVERPORT=51820 `#optional`
      - PEERS=1 `#optional`
      - PEERDNS=auto `#optional`
      - INTERNAL_SUBNET=10.13.13.0 `#optional`
      - ALLOWEDIPS=0.0.0.0/0 `#optional`
      - LOG_CONFS=true `#optional`
    network_mode: host
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  modules:
    name: wireguard-modules
  config:
    name: wireguard-config
