---
- name: Basic Setup
  hosts: localhost
  tasks:
    - name: update & upgrade
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: install essentials
      apt:
        pkg:
          - build-essential
          - git
          - gcc
          - g++
          - make
          - curl
          - wget
          - vim
          - nano
          - apt-transport-https
          - ca-certificates
        state: latest

    - name: install python
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
          - python-is-python3
        state: latest
