name: Publish C to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "C/*"
      - ".github/workflows/c.yml"
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push C Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: vineelsai/gcc:latest
          file: ./C/Dockerfile
