name: Run Schedule Update for GitHub Issues and Keep Notes Sync

on:
    push:
        branches: ["main"]
        paths:
            - "Automations/GitHub Issues Keep Notes Sync/**"
            - ".github/workflows/Sync.yml"
    schedule:
        - cron: "0 7 * * *"

permissions:
    contents: read

env:
    EMAIL: ${{ secrets.EMAIL }}
    PASSWORD: ${{ secrets.PASSWORD }}
    GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Run Update
              working-directory: Automations/GitHub Issues Keep Notes Sync
              run: |
                  pip install --upgrade pip
                  pip install -r requirements.txt
                  python main.py
